// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6nUSmJBy6DfjdMbJdgXpo-HEk4q5sxg',
    appId: '1:395932082027:web:025a0d32f3d3303425762e',
    messagingSenderId: '395932082027',
    projectId: 'compras-4e626',
    authDomain: 'compras-4e626.firebaseapp.com',
    storageBucket: 'compras-4e626.appspot.com',
    measurementId: 'G-JLBKWHEERD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_YUhQ-yj23cuu9DbqyL-6wxkvEhwplM',
    appId: '1:395932082027:android:91ffaa59bb537ddb25762e',
    messagingSenderId: '395932082027',
    projectId: 'compras-4e626',
    storageBucket: 'compras-4e626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnroa94dTV6ooI37fcGD_cL5nH5do5KAU',
    appId: '1:395932082027:ios:c39157301661e43d25762e',
    messagingSenderId: '395932082027',
    projectId: 'compras-4e626',
    storageBucket: 'compras-4e626.appspot.com',
    iosBundleId: 'com.example.amazonCompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnroa94dTV6ooI37fcGD_cL5nH5do5KAU',
    appId: '1:395932082027:ios:c39157301661e43d25762e',
    messagingSenderId: '395932082027',
    projectId: 'compras-4e626',
    storageBucket: 'compras-4e626.appspot.com',
    iosBundleId: 'com.example.amazonCompras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU6nUSmJBy6DfjdMbJdgXpo-HEk4q5sxg',
    appId: '1:395932082027:web:7b0dcb799e68e95625762e',
    messagingSenderId: '395932082027',
    projectId: 'compras-4e626',
    authDomain: 'compras-4e626.firebaseapp.com',
    storageBucket: 'compras-4e626.appspot.com',
    measurementId: 'G-33GFKMPBNG',
  );
}
